baseURL = "http://strakaliuke.lt/"
#baseURL = "http://localhost:1313"
#languageCode = "en-us"
languageCode = "lt"
title = "Strakaliukė"
theme = "hugo_theme_robust"
publishDir = "docs"

[params]
    description = "Darbai namų jaukumui"

[taxonomies]
    #tag = "tags"
    #category = "categories"  # this could be used to display categories of services
    #series = "series"
    paslaugos = "services"