
baseURL = "https://prp1.github.io/auksaranke/"
languageCode = "en-us"
title = "Auksarankė"
theme = "hugo_theme_robust"
publishDir = "docs"

[params]
    author = "Calin Tataru"
    description = "Personal blog theme powered by Hugo 2"
    githubUsername = "#"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
    paslauga = "paslaugos"
    service = "services"