baseURL = "http://example.com/"
languageCode = "en-us"
title = "Minimal"
theme = "minimal"

[params]
    author = "Calin Tataru"
    description = "Personal blog theme powered by Hugo 2"
    githubUsername = "#"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
    paslauga = "paslaugos"
    service = "services"